# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  eas_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Login to Expo
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Trigger build
          command: npx eas-cli build --platform android --non-interactive

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/Prayer-Circle/code

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  build_app_workflow:
    jobs:
      - eas_build:
          filters:
            branches:
              only: master
